apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://34.78.170.254:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: prom
    jsonData:
      httpMethod: GET
