# This file can be used to spin up a local development environment for openteleemtry-benchmark.
# It automatically compiles `benchd`, the benchmarking client.
# To force a recompilation, run `docker-compose up --build`.

version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.41.0
    ports:
      - "6831:6831"
      - "14268:14268"
      - "4317:4317"
      - "8888:8888"
    volumes:
      - ./examples/otelcol-config.example.yaml:/config/otel-collector.yaml
    command:
      - --config=/config/otel-collector.yaml

  benchd:
    build: .
    ports:
      - "2112:2112"
