version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.41.0
    ports:
      - "6831:6831"
      - "14268:14268"
      - "4317:4317"
      - "8888:8888"
    volumes:
      - ./otelcol-config.example.yaml:/config/otel-collector.yaml
    command:
      - --config=/config/otel-collector.yaml

  benchd:
    build: .
    ports:
      - "2112:2112"
