# This file can be used to spin up a local development environment for openteleemtry-benchmark.
# It automatically compiles `benchd`, the benchmarking client.
# To force a recompilation, run `docker-compose up --build`.

version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.41.0
    ports:
      - "6831:6831"
      - "14268:14268"
      - "4317:4317"
      - "8888:8888"
    volumes:
      - ./examples/otelcol-config.example.yaml:/config/otel-collector.yaml
    command:
      - --config=/config/otel-collector.yaml

  benchd:
    build: .
    ports:
      - "7666:7666"

  grafana:
    image: grafana/grafana:8.1.5
    volumes:
      - ./terraform/grafana/datasource:/etc/grafana/provisioning/datasources
      - ./terraform/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./terraform/grafana/dashboards/boards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
