receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: http://benchd:7666/v1/traces # This is where `benchd` listens

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
      