{
 "title": "Benchmarking Client",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(benchd_manager_active_workers_count) by (name)",
     "legendFormat": "plan {{name}}"
    }
   ]
  },
  {
   "title": "Traces Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(benchd_manager_traces_sent_count) by (name)",
     "legendFormat": "plan {{name}}"
    }
   ]
  },
  {
   "title": "Average Round Trip Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " rate(benchd_worker_trace_roundtrip_duration_seconds_sum[1m])/\n rate(benchd_worker_trace_roundtrip_duration_seconds_count[1m])",
     "legendFormat": "average {{name}}"
    },
    {
     "expr": "benchd_worker_trace_roundtrip_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "50% {{name}}"
    },
    {
     "expr": "benchd_worker_trace_roundtrip_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "90% {{name}}"
    },
    {
     "expr": "benchd_worker_trace_roundtrip_duration_seconds{quantile=\"0.95\"}",
     "legendFormat": "95% {{name}}"
    },
    {
     "expr": "benchd_worker_trace_roundtrip_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "99% {{name}}"
    }
   ]
  },
  {
   "title": "Traces Sent Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(benchd_manager_traces_sent_count[1m])) by (name)",
     "legendFormat": "plan {{name}}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(benchd_manager_worker_error_count[1m])) by (name,kind)",
     "legendFormat": "plan {{name}} {{kind}}"
    }
   ]
  }
 ]
}